language_google_translate = {'african': 'af',
    'arabic': 'ar',
    'bulgarian': 'bg',
    'simplified chinese': 'zh-cn',
    'traditional chinese': 'zh-tw',
    'chinedse': 'zh-tw',
    'croatian': 'hr',
    'czech': 'cs',
    'danish': 'da',
    'dutch': 'nl',
    'english': 'en',
    'finnish': 'fi',
    'french': 'fr',
    'galicia': 'gl',
    'german': 'de',
    'greek': 'el',
    'hebrew': 'iw',
    'hindi': 'hi',
    'hungarian': 'hu',
    'icelandic': 'is',
    'indonesian': 'id',
    'italian': 'it',
    'japanese': 'ja',
    'canada': 'kn',
    'korea': 'ko',
    'lithuanian': 'lt',
    'malay': 'ms',
    'norwegian': 'nv',
    'polish': 'pl',
    'portuguese': 'pt',
    'romanian': 'ro',
    'russian': 'ru',
    'serbian': 'sr',
    'slovak': 'sk',
    'slovenian': 'sl',
    'spanish': 'es',
    'swedish': 'sv',
    'thai': 'th',
    'turkish': 'tr',
    'ukrainian': 'uk',
    'vietnam': 'vi',
    'zulu': 'zu'
                        }